//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbrellaAlert.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmbrellaAlert.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbrella Alert.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A drizzle..
        /// </summary>
        public static string Drizzle {
            get {
                return ResourceManager.GetString("Drizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare for rain.
        /// </summary>
        public static string DrizzleSubtitle {
            get {
                return ResourceManager.GetString("DrizzleSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization services are disabled in phone settings, therefore we cannot obtain GPS data.
        /// </summary>
        public static string LocationDisabled {
            get {
                return ResourceManager.GetString("LocationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe.
        /// </summary>
        public static string Maybe {
            get {
                return ResourceManager.GetString("Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better watch the skies..
        /// </summary>
        public static string MaybeSubtitle {
            get {
                return ResourceManager.GetString("MaybeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS signal.
        /// </summary>
        public static string NoGPS {
            get {
                return ResourceManager.GetString("NoGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining location....
        /// </summary>
        public static string ObtainingLocation {
            get {
                return ResourceManager.GetString("ObtainingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string RainYes {
            get {
                return ResourceManager.GetString("RainYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget your umbrella!.
        /// </summary>
        public static string RainYesSubtitle {
            get {
                return ResourceManager.GetString("RainYesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-e-es.
        /// </summary>
        public static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And it will be cold..
        /// </summary>
        public static string SnowSubtitle {
            get {
                return ResourceManager.GetString("SnowSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Sunny {
            get {
                return ResourceManager.GetString("Sunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go out and enjoy the sun!.
        /// </summary>
        public static string SunnySubtitle {
            get {
                return ResourceManager.GetString("SunnySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I need an umbrella.
        /// </summary>
        public static string UmbrellaAlert {
            get {
                return ResourceManager.GetString("UmbrellaAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occcured..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather from OpenWeatherMap.
        /// </summary>
        public static string WeatherBy {
            get {
                return ResourceManager.GetString("WeatherBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string WeatherLang {
            get {
                return ResourceManager.GetString("WeatherLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today in {0}?.
        /// </summary>
        public static string WillRainIn {
            get {
                return ResourceManager.GetString("WillRainIn", resourceCulture);
            }
        }
    }
}
